apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cloud-config
  name: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloud-config
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: cloud-config
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              value: myzone
            - name: EUREKA_CLIENT_REGION
              value: default
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              value: http://service-discovery:8761/eureka
            - name: SPRING_ZIPKIN_BASE-URL
              value: http://zipkin:9411
            - name: EUREKA_INSTANCE
              value: "cloud-config"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: cloud-config
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
          image: br14nmat/cloud-config:latest
          name: cloud-config
          ports:
            - containerPort: 9296
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cloud-config
  name: cloud-config
spec:
  ports:
    - name: "9296"
      port: 9296
      targetPort: 9296
  selector:
    io.kompose.service: cloud-config