version: '3'
services: 
  api-gateway-container: 
    image: br14nmat/api-gateway:latest 
    ports: 
      - 8080:8080 
    networks: 
      - microservices_network 
    environment: 
    - SPRING_PROFILES_ACTIVE=dev 
    - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
    - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
    - EUREKA_CLIENT_REGION=default 
    - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
    - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
  proxy-client-container:
    image: br14nmat/proxy-client:latest 
    ports: 
      - 8900:8900 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
  order-service-container: 
    image: br14nmat/order-service:latest 
    ports: 
      - 8300:8300 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/

  payment-service-container: 
    image: br14nmat/payment-service:latest 
    ports: 
      - 8400:8400 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/

  product-service-container: 
    image: br14nmat/product-service:latest 
    ports: 
      - 8500:8500 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/

  shipping-service-container: 
    image: br14nmat/shipping-service:latest 
    networks: 
      - microservices_network 
    ports: 
      - 8600:8600 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/

  user-service-container: 
    image: br14nmat/user-service:latest 
    ports: 
      - 8700:8700 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/

  favourite-service-container: 
    image: br14nmat/favourite-service:latest 
    ports: 
      - 8800:8800 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/

networks: 
  microservices_network: 
    driver: bridge