apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: service-discovery-container
  name: service-discovery-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-discovery-container
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: service-discovery-container
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
            - name: EUREKA_INSTANCE
              value: "service-discovery"
          image: br14nmat/service-discovery:latest
          name: service-discovery-container
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: service-discovery-container
  name: service-discovery-container
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    io.kompose.service: service-discovery-container
  type: LoadBalancer
