pipeline {
    
    agent any

    tools {
        maven "MavenTool"
    }

    environment {
        RESOURCE_GROUP = "taller2"
        AKS_NAME = "taller2brian"
        NAMESPACE = "prod"
    }

    stages {
        stage("Checkout git") {
            steps {
                checkout scmGit(
                    branches: [[name: '*/master']], 
                    extensions: [], 
                    userRemoteConfigs: [[url: 'https://github.com/Br14nMat/ecommerce-microservice-backend-app']]
                )
            }
        }

        
        stage("Run Unit and Integration Tests") {
            steps {

                dir('product-service') {
                    sh 'mvn clean verify'
                }

                dir('payment-service') {
                    sh 'mvn clean verify'
                }
            }
        }
        

        stage('Set subscription') {
            steps {
                withCredentials([string(credentialsId: 'AZURE_SUBSCRIPTION_ID', variable: 'SUBSCRIPTION_ID')]) {
                    sh '''
                        az account set --subscription $SUBSCRIPTION_ID
                    '''
                }
            }
        }

        stage('Kubelogin step') {
            steps {
                sh '''
                    az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_NAME --overwrite-existing
                    kubelogin convert-kubeconfig -l azurecli
                '''
            }
        }

        stage('Deploy core services'){

            steps {
                sh '''

                    kubectl apply -n $NAMESPACE -f k8s/$NAMESPACE/zipkin-deployment.yaml
                    kubectl wait -n $NAMESPACE --for=condition=ready pod -l io.kompose.service=zipkin --timeout=300s

                    kubectl apply -n $NAMESPACE -f k8s/$NAMESPACE/cloud-config-container-deployment.yaml
                    kubectl wait -n $NAMESPACE --for=condition=ready pod -l io.kompose.service=cloud-config --timeout=300s

                    kubectl apply -n $NAMESPACE -f k8s/$NAMESPACE/service-discovery-container-deployment.yaml
                    kubectl wait -n $NAMESPACE --for=condition=ready pod -l io.kompose.service=service-discovery --timeout=300s

                    kubectl apply -n $NAMESPACE -f k8s/$NAMESPACE/api-gateway-container-deployment.yaml
                    kubectl wait -n $NAMESPACE --for=condition=ready pod -l io.kompose.service=api-gateway --timeout=300s

                '''
            }

        }

        stage('Deploy remaining services') {
            steps {
                sh '''
                    kubectl apply -n $NAMESPACE -f k8s/$NAMESPACE/product-service-container-deployment.yaml
                    kubectl wait -n $NAMESPACE --for=condition=ready pod -l io.kompose.service=product-service --timeout=300s

                    kubectl apply -n $NAMESPACE -f k8s/$NAMESPACE/payment-service-container-deployment.yaml
                    kubectl wait -n $NAMESPACE --for=condition=ready pod -l io.kompose.service=payment-service --timeout=300s

                    kubectl apply -n $NAMESPACE -f k8s/$NAMESPACE/order-service-container-deployment.yaml
                    kubectl wait -n $NAMESPACE --for=condition=ready pod -l io.kompose.service=order-service --timeout=300s

                    kubectl apply -n $NAMESPACE -f k8s/$NAMESPACE/user-service-container-deployment.yaml
                    kubectl wait -n $NAMESPACE --for=condition=ready pod -l io.kompose.service=user-service --timeout=300s

                '''
            }
        }


        stage('Port Forward Multiple Services') {
            steps {
                script {
                    sh '''
                        # Port forward Product Service
                        kubectl port-forward service/product-service 8500:8500 -n ${NAMESPACE} &
                        echo $! > portforward-product.pid

                        # Port forward Order Service
                        kubectl port-forward service/order-service 8300:8300 -n ${NAMESPACE} &
                        echo $! > portforward-order.pid

                        # Port forward User Service
                        kubectl port-forward service/user-service 8700:8700 -n ${NAMESPACE} &
                        echo $! > portforward-user.pid

                        # Espera unos segundos a que todos los port forwards estén listos
                        sleep 10
                    '''
                }
            }
        }

        stage('Run E2E Tests') {
            steps {
                sh '''
                    newman run e2e/e2e-product-service.json

                    newman run e2e/e2e-user-service.json

                    newman run e2e/e2e-order-service.json
                '''
            }
        }


        stage('Locust Tests') {
            steps {
                sh '''
                    
                    mkdir -p locust/locust_output/product
                    
                    locust -f locust/locustfile-product.py \
                    --host=http://localhost:8500/product-service \
                    --users=10 \
                    --spawn-rate=2 \
                    --run-time=1m \
                    --headless \
                    --html=locust/locust_output/product/locust_report.html


                    mkdir -p locust/locust_output/order
                    
                    locust -f locust/locustfile-order.py \
                    --host=http://localhost:8300/order-service \
                    --users=10 \
                    --spawn-rate=2 \
                    --run-time=1m \
                    --headless \
                    --html=locust/locust_output/order/locust_report.html


                    mkdir -p locust/locust_output/user
                    
                    locust -f locust/locustfile-user.py \
                    --host=http://localhost:8700/user-service \
                    --users=10 \
                    --spawn-rate=2 \
                    --run-time=1m \
                    --headless \
                    --html=locust/locust_output/user/locust_report.html
                    
                '''
            }
            
        }


        stage('Stop Port Forwards') {
            steps {
                script {
                    sh '''
                        kill $(cat portforward-product.pid) || true
                        kill $(cat portforward-order.pid) || true
                        kill $(cat portforward-user.pid) || true
                    '''
                }
            }
        }

        stage('Generate Release Notes') {
                steps {
                    script {
                        
                        def version = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                        def date = sh(script: "date '+%Y-%m-%d %H:%M:%S'", returnStdout: true).trim()
                        def commitLogs = sh(script: "git log -5 --pretty=format:'- %s (%an)'", returnStdout: true).trim()
                        
                        sh 'mkdir -p release_notes'
                        
                        def releaseNotes = """
                            # Release Notes - ${version}

                            **Fecha y hora:** ${date}  
                            **Ambiente:** ${NAMESPACE}  

                            ## ✅ Cambios recientes
                            ${commitLogs}

                            ## 🧪 Resultados esperados
                            - Pruebas unitarias e integradas: ✅ OK
                            - Pruebas E2E: ✅ OK 
                            - Pruebas de carga Locust: ✅ OK (ver Newman report) 
                                - Archivos: locust_output/*/locust_report.html

                            ## 📎 Referencia
                            - Build: #${env.BUILD_NUMBER}
                            - Commit: ${version}
                            - Branch: master
                            """
                        writeFile file: "release_notes/release-${version}.md", text: releaseNotes
                        
                    }
                }
        }

        stage('Archive JaCoCo Reports') {
            steps {
                script {
                    sh 'mkdir -p coverage-reports/product-service'
                    sh 'mkdir -p coverage-reports/payment-service'

                    sh 'cp -r product-service/target/site/jacoco/* coverage-reports/product-service/'
                    sh 'cp -r payment-service/target/site/jacoco/* coverage-reports/payment-service/'
                }

                archiveArtifacts artifacts: 'coverage-reports/**/*.html', fingerprint: true
            }
        }

    }

    post {
        success {
            script {
                def successAttachment = [[
                    text: "✅ El pipeline de ${env.NAMESPACE} se ejecutó correctamente.", 
                    fallback: 'El pipeline fue exitoso.',
                    color: '#36a64f'
                ]]
                slackSend(channel: "#general-ingesoftv", attachments: successAttachment) 
            }
        }
        failure {
            script {
                def failureAttachment = [[
                    text: "❌ El pipeline de ${env.NAMESPACE} falló. Revisa los logs para más detalles.", 
                    fallback: 'El pipeline falló.',
                    color: '#ff0000'
                ]]
                slackSend(channel: "#general-ingesoftv", attachments: failureAttachment)
            }
        }
    }

}
