pipeline{
    agent any 
    tools {
        maven "MavenTool"
    }
    
    stages {
        stage("Checkout git") {
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Br14nMat/ecommerce-microservice-backend-app']])
            }
        }
        stage("Build Cloud Config") {
            steps {
                dir('cloud-config') {
                    sh 'mvn clean install' 
                }
            }
        }
        stage("Build and Push Docker Image") {
            steps {
                script {
                    withDockerRegistry(
                        credentialsId: 'dockerhub-credentials' 
                    ) {
                        sh 'docker build -t br14nmat/cloud-config:latest -f cloud-config/Dockerfile .'
                        sh 'docker push br14nmat/cloud-config:latest'
                    }
                }
            }
        }
        
    }
}