pipeline {
    
    agent any

    tools {
        maven "MavenTool"
    }

    environment {
        RESOURCE_GROUP = "taller2"
        AKS_NAME = "taller2brian"
        NAMESPACE = "stage"
        SERVICE = 'product-service'
    }

    stages {
        stage("Checkout git") {
            steps {
                checkout scmGit(
                    branches: [[name: '*/master']], 
                    extensions: [], 
                    userRemoteConfigs: [[url: 'https://github.com/Br14nMat/ecommerce-microservice-backend-app']]
                )
            }
        }

        
        stage("Run Unit and Integration Tests") {
            steps {
                dir("${SERVICE}") {
                    sh 'mvn test'
                }
            }
        }


        stage("Build Product Service") {
            steps {
                dir("${SERVICE}") {
                    sh 'mvn clean install -DskipTests' 
                }
            }
        }
        

        stage('Set subscription') {
            steps {
                withCredentials([string(credentialsId: 'AZURE_SUBSCRIPTION_ID', variable: 'SUBSCRIPTION_ID')]) {
                    sh '''
                        az account set --subscription $SUBSCRIPTION_ID
                    '''
                }
            }
        }

        stage('Kubelogin step') {
            steps {
                sh '''
                    az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_NAME --overwrite-existing
                    kubelogin convert-kubeconfig -l azurecli
                '''
            }
        }

        stage('Desplegar manifiestos') {
            steps {
                sh '''
                    kubectl apply -n $NAMESPACE -f k8s/$NAMESPACE/$SERVICE-container-deployment.yaml
                    kubectl wait -n $NAMESPACE --for=condition=ready pod -l io.kompose.service=$SERVICE-container --timeout=200s
                '''
            }
        }

        
        stage('Port Forward') {
            steps {
                script {
                    sh '''
                        kubectl port-forward service/${SERVICE}-container 8500:8500 -n ${NAMESPACE} &
                        echo $! > portforward.pid
                        sleep 5  # Espera unos segundos para que esté disponible
                    '''
                }
            }
        }

        stage('Run E2E Tests') {
            steps {
                sh '''
                    newman run e2e/e2e-product-service.json \
                        --env-var baseUrl=http://localhost:8500
                '''
            }
        }

        stage('Cleanup Port Forward') {
            steps {
                sh '''
                    kill $(cat portforward.pid) || true
                    rm -f portforward.pid
                '''
            }
        }


    }
}
