apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: api-gateway-container
  name: api-gateway-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway-container
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: api-gateway-container
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: stage
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
            - name: EUREKA_CLIENT_REGION
              value: default
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              value: myzone
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              value: http://service-discovery-container:8761/eureka
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery-container:8761/eureka/
            - name: EUREKA_INSTANCE
              value: "api-gateway"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: api-gateway
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
          image: br14nmat/api-gateway:latest
          name: api-gateway-container
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: api-gateway-container
  name: api-gateway-container
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: api-gateway-container
  type: LoadBalancer
