apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: shipping-service
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shipping-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: shipping-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: stage
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              value: myzone
            - name: EUREKA_CLIENT_REGION
              value: default
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              value: http://service-discovery:8761/eureka
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
            - name: SPRING_ZIPKIN_BASE-URL
              value: http://zipkin:9411
            - name: EUREKA_INSTANCE
              value: "shipping-service"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: shipping-service
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
          image: br14nmat/shipping-service:latest
          name: shipping-service
          ports:
            - containerPort: 8600
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: shipping-service
  name: shipping-service
spec:
  ports:
    - name: "8600"
      port: 8600
      targetPort: 8600
  selector:
    io.kompose.service: shipping-service