apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      labels:
        io.kompose.service: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/order-service/actuator/prometheus"
        prometheus.io/port: "8300"
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: stage
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              value: myzone
            - name: EUREKA_CLIENT_REGION
              value: default
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              value: http://service-discovery:8761/eureka
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
            - name: SPRING_ZIPKIN_BASE-URL
              value: http://zipkin:9411
            - name: EUREKA_INSTANCE
              value: "user-service"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: user-service
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
          image: br14nmat/user-service:latest
          name: user-service
          ports:
            - containerPort: 8700
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "8700"
      port: 8700
      targetPort: 8700
  selector:
    io.kompose.service: user-service
