apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      io.kompose.service: order-service
  namespaceSelector:
    matchNames:
      - stage
  endpoints:
    - port: http
      path: /order-service/actuator/prometheus
      interval: 15s
