apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      io.kompose.service: product-service
  namespaceSelector:
    matchNames:
      - stage
  endpoints:
    - port: "8500"
      path: /product-service/actuator/prometheus
      interval: 15s
