apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      io.kompose.service: user-service
  namespaceSelector:
    matchNames:
      - stage
  endpoints:
    - port: "8700"
      path: /user-service/actuator/prometheus
      interval: 15s
